# soal 1

In [3]:
import pandas as pd
import numpy as np

In [4]:
beta = 1
qstar = 0.2
g = 9.81
b = 15
T = b
n = 0.013
l = 35
s0= 0.021
#-------------------
Q = 4.85 #assumed 
q = Q / b
yc = ((q**2) / g)**(1/3)
P = (2 * yc) + 15
R = (yc * b) / ((2 * yc) + 15)
#-------------------
parantez = ( s0 - (((n**2) * g * P) / (beta * T * (R**(1/3)) )) )**3 
makhraj = g * (T**2) * parantez
soorat = 8 * beta * (qstar**2)
#-------------------------------
x = soorat / makhraj
print("x in %f meter from start point @ upstream"%x)
print("Q is %f m^3/s and yc equal to %f meter"%(qstar*x,yc))

x in 24.263621 meter from start point @ upstream
Q is 4.852724 m^3/s and yc equal to 0.220061 meter

In [65]:
from numpy import arange
#bala dast : zire bohrani
#yc == 0.220061 @ x = 24.26
X = [24.25] + [i for i in range(20, 0, -1)]  + [0]
z0 = lambda X: s0 * X
Z0 = []
for i in X:
    Z0.append(z0(i))
Y = [yc, 0.21] + [(0.21- (0.001* i)) for i in range(1, 21)]
Z = [Z0[i]+ Y[i] for i in range(len(Z0))]
A = [Y[i] * b for i in range(len(Y))]
Q = [0.2 * X[i] for i in range(len(x))]
V = [Q[i] / A[i] for i in range(len(Q))]
R = [A[i] / (2 * Y[i] + b) for i in range(len(Y))]
Sf = [(V[i]*(n**2)) / ((R[i]**(4/3)) * A[i]**4) for i in range(len(V))]
'''
z = [0 for i in range(0, 35)]
y = [0 for i in range(0, 35)]
A = [0 for i in range(0, 35)]
Q = [0 for i in range(0, 35)]
V = [0 for i in range(0, 35)]
'''
d = {"X": X, 'z0': Z0,'Y':Y, 'z': Z, 'A':A, 'Q':Q, 'V':V, 'R': R, 'Sf': Sf}
upstream = pd.DataFrame(d)
upstream

,X,z0,Y,z,A,Q,V,R,Sf
0,24.25,0.50925,0.220061,0.729311,3.300922,4.85,1.469287,0.213789,0.000016
1,20.00,0.42000,0.210000,0.630000,3.150000,4.00,1.269841,0.204280,0.000018
2,19.00,0.39900,0.209000,0.608000,3.135000,3.80,1.212121,0.203334,0.000018
3,18.00,0.37800,0.208000,0.586000,3.120000,3.60,1.153846,0.202387,0.000017
4,17.00,0.35700,0.207000,0.564000,3.105000,3.40,1.095008,0.201440,0.000017
5,16.00,0.33600,0.206000,0.542000,3.090000,3.20,1.035599,0.200493,0.000016
6,15.00,0.31500,0.205000,0.520000,3.075000,3.00,0.975610,0.199546,0.000016
7,14.00,0.29400,0.204000,0.498000,3.060000,2.80,0.915033,0.198598,0.000015
8,13.00,0.27300,0.203000,0.476000,3.045000,2.60,0.853859,0.197650,0.000015
9,12.00,0.25200,0.202000,0.454000,3.030000,2.40,0.792079,0.196702,0.000014
10,11.00,0.23100,0.201000,0.432000,3.015000,2.20,0.729685,0.195754,0.000013
11,10.00,0.21000,0.200000,0.410000,3.000000,2.00,0.666667,0.194805,0.000012
12,9.00,0.18900,0.199000,0.388000,2.985000,1.80,0.603015,0.193856,0.000011
13,8.00,0.16800,0.198000,0.366000,2.970000,1.60,0.538721,0.192907,0.000010
14,7.00,0.14700,0.197000,0.344000,2.955000,1.40,0.473773,0.191958,0.000009
15,6.00,0.12600,0.196000,0.322000,2.940000,1.20,0.408163,0.191008,0.000008
16,5.00,0.10500,0.195000,0.300000,2.925000,1.00,0.341880,0.190058,0.000007
17,4.00,0.08400,0.194000,0.278000,2.910000,0.80,0.274914,0.189108,0.000006
18,3.00,0.06300,0.193000,0.256000,2.895000,0.60,0.207254,0.188158,0.000005
19,2.00,0.04200,0.192000,0.234000,2.880000,0.40,0.138889,0.187207,0.000003
20,1.00,0.02100,0.191000,0.212000,2.865000,0.20,0.069808,0.186257,0.000002
21,0.00,0.00000,0.190000,0.190000,2.850000,0.00,0.000000,0.185306,0.000000

In [66]:
Qs = list(upstream.Q)
Vs = list(upstream.V)
Ys = list(upstream.Y)
Sfs = list(upstream.Sf)
Xs = list(upstream.X)
deltaQ = []
deltaV = []
deltaY = []
XinSf = list()

for i in range(len(Qs)):
    j = i + 1
    try:
        delta = Qs[i] - Qs[j]
        deltaQ.append(delta)
    except:
        KeyError

for i in range(len(Vs)):
    j = i + 1
    try:
        delta = Vs[i] - Vs[j]
        deltaV.append(delta)
    except:
        KeyError

for i in range(len(Ys)):
    j = i + 1
    try:
        delta = Ys[i] - Ys[j]
        deltaY.append(delta)
    except:
        KeyError

for i in range(len(Sfs)):
    zarb = Sfs[i] * Xs[i]
    XinSf.append(zarb)
XinSf = XinSf[1:]
Yfinal = []
for i in range(len(deltaY)):
    final = deltaY[i] + XinSf[i]
    Yfinal.append(final)
dd = {"delta Q": deltaQ, "delta V": deltaV, "delta Y": deltaY, "X * Sfbar": XinSf, "Y final": Yfinal}
upstream_delta = pd.DataFrame(dd)
upstream_delta

    delta Q   delta V   delta Y  X * Sfbar   Y final
0      0.85  0.199445  0.010061   0.000362  0.010424
1      0.20  0.057720  0.001000   0.000337  0.001337
2      0.20  0.058275  0.001000   0.000312  0.001312
3      0.20  0.058838  0.001000   0.000287  0.001287
4      0.20  0.059409  0.001000   0.000262  0.001262
5      0.20  0.059989  0.001000   0.000237  0.001237
6      0.20  0.060577  0.001000   0.000213  0.001213
7      0.20  0.061174  0.001000   0.000190  0.001190
8      0.20  0.061780  0.001000   0.000167  0.001167
9      0.20  0.062394  0.001000   0.000144  0.001144
10     0.20  0.063018  0.001000   0.000123  0.001123
11     0.20  0.063652  0.001000   0.000103  0.001103
12     0.20  0.064295  0.001000   0.000084  0.001084
13     0.20  0.064947  0.001000   0.000066  0.001066
14     0.20  0.065610  0.001000   0.000050  0.001050
15     0.20  0.066283  0.001000   0.000036  0.001036
16     0.20  0.066966  0.001000   0.000024  0.001024
17     0.20  0.067660  0.001000   0.000014  0.001014
18     0.20  0.068365  0.001000   0.000006  0.001006
19     0.20  0.069081  0.001000   0.000002  0.001002
20     0.20  0.069808  0.001000   0.000000  0.001000

### maghadir tafavote fahesh ba farz haye anjam shode nadarad pas Y haye farz shode morede ghabool ast.

In [78]:
#payin dast : foghe bohrani
#yc == 0.220061 @ x = 24.26
X = [24.25] + [i for i in range(25, 36)]

z0 = lambda X: s0 * X
Z0 = []
for i in X:
    Z0.append(z0(i))
Y = [yc, 0.20] + [(0.21- (0.001* i)) for i in range(1, 11)]
Z = [Z0[i]+ Y[i] for i in range(len(Z0))]
A = [Y[i] * b for i in range(len(Y))]
Q = [0.2 * X[i] for i in range(len(X))]
V = [Q[i] / A[i] for i in range(len(Q))]
R = [A[i] / (2 * Y[i] + b) for i in range(len(Y))]
Sf = [(V[i]*(n**2)) / ((R[i]**(4/3)) * A[i]**4) for i in range(len(V))]
ddd = {"X": X, 'z0': Z0, "Y": Y, 'Z': Z, 'A': A, "Q": Q,'V':V,"R":R, "Sf": Sf}
downstream = pd.DataFrame(ddd)
downstream

,X,z0,Y,Z,A,Q,V,R,Sf
0,24.25,0.50925,0.220061,0.729311,3.300922,4.85,1.469287,0.213789,0.000016
1,25.00,0.52500,0.200000,0.725000,3.000000,5.00,1.666667,0.194805,0.000031
2,26.00,0.54600,0.209000,0.755000,3.135000,5.20,1.658692,0.203334,0.000024
3,27.00,0.56700,0.208000,0.775000,3.120000,5.40,1.730769,0.202387,0.000026
4,28.00,0.58800,0.207000,0.795000,3.105000,5.60,1.803543,0.201440,0.000028
5,29.00,0.60900,0.206000,0.815000,3.090000,5.80,1.877023,0.200493,0.000030
6,30.00,0.63000,0.205000,0.835000,3.075000,6.00,1.951220,0.199546,0.000032
7,31.00,0.65100,0.204000,0.855000,3.060000,6.20,2.026144,0.198598,0.000034
8,32.00,0.67200,0.203000,0.875000,3.045000,6.40,2.101806,0.197650,0.000036
9,33.00,0.69300,0.202000,0.895000,3.030000,6.60,2.178218,0.196702,0.000038
10,34.00,0.71400,0.201000,0.915000,3.015000,6.80,2.255390,0.195754,0.000041
11,35.00,0.73500,0.200000,0.935000,3.000000,7.00,2.333333,0.194805,0.000043

In [81]:
Qs = list(downstream.Q)
Vs = list(downstream.V)
Ys = list(downstream.Y)
Sfs = list(downstream.Sf)
Xs = list(downstream.X)
deltaQ = []
deltaV = []
deltaY = []
XinSf = list()

for i in range(len(Qs)):
    j = i + 1
    try:
        delta = Qs[j] - Qs[i]
        deltaQ.append(delta)
    except:
        KeyError

for i in range(len(Vs)):
    j = i + 1
    try:
        delta = Vs[j] - Vs[i]
        deltaV.append(delta)
    except:
        KeyError

for i in range(len(Ys)):
    j = i + 1
    try:
        delta = Ys[j] - Ys[i]
        deltaY.append(delta)
    except:
        KeyError

for i in range(len(Sfs)):
    zarb = Sfs[i] * Xs[i]
    XinSf.append(zarb)
XinSf = XinSf[1:]
Yfinal = []
for i in range(len(deltaY)):
    final = deltaY[i] + XinSf[i]
    Yfinal.append(final)
dddd = {"delta Q": deltaQ, "delta V": deltaV, "delta Y": deltaY, "X * Sfbar": XinSf, "Y final": Yfinal}
downstream_delta = pd.DataFrame(dddd)
downstream_delta

    delta Q   delta V   delta Y  X * Sfbar   Y final
0      0.15  0.197380 -0.020061   0.000770 -0.019292
1      0.20 -0.007974  0.009000   0.000631  0.009631
2      0.20  0.072077 -0.001000   0.000701 -0.000299
3      0.20  0.072773 -0.001000   0.000778 -0.000222
4      0.20  0.073480 -0.001000   0.000860 -0.000140
5      0.20  0.074197 -0.001000   0.000949 -0.000051
6      0.20  0.074924 -0.001000   0.001045  0.000045
7      0.20  0.075662 -0.001000   0.001148  0.000148
8      0.20  0.076412 -0.001000   0.001260  0.000260
9      0.20  0.077172 -0.001000   0.001380  0.000380
10     0.20  0.077944 -0.001000   0.001509  0.000509